[package]
name = "bybe"
version = "1.3.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.75.0"

description = "Beyond Your Bestiary Explorer (BYBE) is a web service that provides tools to help Pathfinder 2e Game Masters."
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE"
license = "MIT"
keywords = ["webservice", "pathfinder"]
publish = false

build = "build/main.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "4.6.0"
actix-cors = "0.7.0"
actix-web-validator = "5.0.1"
# Cannot be updated until actix-web updates validator dependency
validator = {version="0.16.1", features = ["derive"]}

utoipa = { version = "4.2.3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "7.0.1", features = ["actix-web"] }

sqlx = { version = "0.7.4", features = ["runtime-async-std", "sqlite"] }
cached = { version = "0.51.3", features = ["async"] }

anyhow = "1.0.86"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
strum = {version="0.26.2", features = ["derive"]}
rand = "0.9.0-alpha.1"
counter = "0.5.7"
dotenvy = "0.15.7"
regex = "1.10.4"

env_logger = "0.11.3"
log = "0.4.21"
maplit = "1.0.2"
num-traits = "0.2.19"

[build-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.86"
sqlx = {version = "0.7.4", features = ["runtime-async-std", "sqlite"]}
dotenvy = "0.15.7"
