[package]
name = "bybe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
actix-web-validator = "5.0.1"
validator = {version="0.16.1", features = ["derive"]}

utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }

redis = {version = "0.23.0-beta.1", features = ["json"]}

anyhow = "1.0.75"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = {version="0.25", features = ["derive"]}
rand = "0.8.5"
counter = "0.5.7"

env_logger = "0.10"
log = "0.4"
lazy_static = "1.4.0"
maplit = "1"

tokio = "1.29"
