[package]
name = "bybe"
version = "2.1.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.75.0"

description = "Beyond Your Bestiary Explorer (BYBE) is a web service that provides tools to help Pathfinder 2e Game Masters."
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE"
license = "MIT"
keywords = ["webservice", "pathfinder"]
publish = false

build = "build/main.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
validator = {version="0.18.1", features = ["derive"]}

utoipa = { version = "5.0.0-alpha.2", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "7.1.1-alpha.1", features = ["actix-web"] }

sqlx = { version = "0.8.1", features = ["runtime-async-std", "sqlite"] }
cached = { version = "0.53.1", features = ["async"] }

anyhow = "1.0.86"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
strum = {version="0.26.3", features = ["derive"]}
fastrand = "2.1.1"
counter = "0.6.0"
ordered-float = { version = "4", features = ["serde"]}
num-traits = "0.2.19"
maplit = "1.0.2"
itertools = "0.13.0"

regex = "1.10.6"

dotenvy = "0.15.7"

env_logger = "0.11.5"
log = "0.4.22"
once_cell = "1.19.0"

[build-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.86"
sqlx = {version = "0.8.1", features = ["runtime-async-std", "sqlite"]}
dotenvy = "0.15.7"
