[package]
name = "bybe"
version = "1.3.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.75.0"

description = "Beyond Your Bestiary Explorer (BYBE) is a web service that provides tools to help Pathfinder 2e Game Masters."
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE"
license = "MIT"
keywords = ["webservice", "pathfinder"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "4.4.1"
actix-cors = "0.7.0"
actix-web-validator = "5.0.1"
validator = {version="0.16.1", features = ["derive"]}

utoipa = { version = "4.2.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }

sqlx = { version = "0.7.3", features = ["runtime-async-std", "sqlite"] }
mini-moka = "0.10.3"

anyhow = "1.0.79"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
strum = {version="0.26.1", features = ["derive"]}
rand = "0.8.5"
counter = "0.5.7"

env_logger = "0.11.1"
log = "0.4.20"
maplit = "1.0.2"
