[package]
name = "bybe"
version = "1.0.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.66.1"

description = "Beyond Your Bestiary Explorer (BYBE) is a web service that provides tools to help Pathfinder 2e Game Masters."
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE"
license = "MIT"
keywords = ["webservice", "pathfinder"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
actix-web-validator = "5.0.1"
validator = {version="0.16.1", features = ["derive"]}

utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }

sqlx = { version = "0.7.2", features = ["runtime-async-std", "sqlite"] }
mini-moka = "0.10.2"

anyhow = "1.0.75"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = {version="0.25", features = ["derive"]}
rand = "0.8.5"
counter = "0.5.7"

env_logger = "0.10"
log = "0.4"
lazy_static = "1.4.0"
maplit = "1"
