[package]
name = "bybe"
version = "1.3.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.77.1"

description = "Beyond Your Bestiary Explorer (BYBE) is a web service that provides tools to help Pathfinder 2e Game Masters."
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE"
license = "MIT"
keywords = ["webservice", "pathfinder"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "4.5.1"
actix-cors = "0.7.0"
actix-web-validator = "5.0.1"
validator = {version="0.16.1", features = ["derive"]}

utoipa = { version = "4.2.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }

sqlx = { version = "0.7.4", features = ["runtime-async-std", "sqlite"] }
mini-moka = "0.10.3"

anyhow = "1.0.81"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
strum = {version="0.26.2", features = ["derive"]}
rand = "0.9.0-alpha.0"
counter = "0.5.7"
dotenvy = "0.15.7"
regex = "1.10.4"

env_logger = "0.11.3"
log = "0.4.21"
maplit = "1.0.2"
num-traits = "0.2.18"
