on:
  pull_request:
    types: [opened, synchronize, edited, review_requested, ready_for_review]
name: PR

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: mbrobbel/rustfmt-check@345558b33101faacd2fc72233e5e9df2c4cdc98f #0.23.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, rustfmt, clippy
      - uses: taiki-e/install-action@e67fa11c4b9316fa714ddf0abed07a0c3143b95b #2.87.4
        with:
          tool: cargo-udeps
      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
